"""Variable enum auto-generated from Open-Meteo OpenAPI spec.

DO NOT EDIT. Regenerate via `just regen-variables`.
Source: https://raw.githubusercontent.com/open-meteo/open-meteo/main/openapi.yml
"""

from enum import StrEnum


class Variable(StrEnum):
    """Weather variable names accepted by the Open-Meteo forecast API."""

    APPARENT_TEMPERATURE = "apparent_temperature"
    APPARENT_TEMPERATURE_MAX = "apparent_temperature_max"
    APPARENT_TEMPERATURE_MIN = "apparent_temperature_min"
    CLOUD_COVER = "cloud_cover"
    CLOUD_COVER_HIGH = "cloud_cover_high"
    CLOUD_COVER_LOW = "cloud_cover_low"
    CLOUD_COVER_MID = "cloud_cover_mid"
    DEW_POINT_2M = "dew_point_2m"
    DIFFUSE_RADIATION = "diffuse_radiation"
    DIRECT_NORMAL_IRRADIANCE = "direct_normal_irradiance"
    DIRECT_RADIATION = "direct_radiation"
    ET0_FAO_EVAPOTRANSPIRATION = "et0_fao_evapotranspiration"
    EVAPOTRANSPIRATION = "evapotranspiration"
    FREEZING_LEVEL_HEIGHT = "freezing_level_height"
    PRECIPITATION = "precipitation"
    PRECIPITATION_HOURS = "precipitation_hours"
    PRECIPITATION_SUM = "precipitation_sum"
    PRESSURE_MSL = "pressure_msl"
    RELATIVE_HUMIDITY_2M = "relative_humidity_2m"
    SHORTWAVE_RADIATION = "shortwave_radiation"
    SHORTWAVE_RADIATION_SUM = "shortwave_radiation_sum"
    SNOW_HEIGHT = "snow_height"
    SOIL_MOISTURE_0_1CM = "soil_moisture_0_1cm"
    SOIL_MOISTURE_1_3CM = "soil_moisture_1_3cm"
    SOIL_MOISTURE_27_81CM = "soil_moisture_27_81cm"
    SOIL_MOISTURE_3_9CM = "soil_moisture_3_9cm"
    SOIL_MOISTURE_9_27CM = "soil_moisture_9_27cm"
    SOIL_TEMPERATURE_0CM = "soil_temperature_0cm"
    SOIL_TEMPERATURE_18CM = "soil_temperature_18cm"
    SOIL_TEMPERATURE_54CM = "soil_temperature_54cm"
    SOIL_TEMPERATURE_6CM = "soil_temperature_6cm"
    SUNRISE = "sunrise"
    SUNSET = "sunset"
    TEMPERATURE_2M = "temperature_2m"
    TEMPERATURE_2M_MAX = "temperature_2m_max"
    TEMPERATURE_2M_MIN = "temperature_2m_min"
    UV_INDEX_CLEAR_SKY_MAX = "uv_index_clear_sky_max"
    UV_INDEX_MAX = "uv_index_max"
    VAPOUR_PRESSURE_DEFICIT = "vapour_pressure_deficit"
    WEATHER_CODE = "weather_code"
    WIND_DIRECTION_10M = "wind_direction_10m"
    WIND_DIRECTION_10M_DOMINANT = "wind_direction_10m_dominant"
    WIND_DIRECTION_120M = "wind_direction_120m"
    WIND_DIRECTION_180M = "wind_direction_180m"
    WIND_DIRECTION_80M = "wind_direction_80m"
    WIND_GUSTS_10M = "wind_gusts_10m"
    WIND_GUSTS_10M_MAX = "wind_gusts_10m_max"
    WIND_SPEED_10M = "wind_speed_10m"
    WIND_SPEED_10M_MAX = "wind_speed_10m_max"
    WIND_SPEED_120M = "wind_speed_120m"
    WIND_SPEED_180M = "wind_speed_180m"
    WIND_SPEED_80M = "wind_speed_80m"
